"""MW5 Mercs inventory item catalog (weapons / equipment / ammo).

Sources, in order of trust:
  1. Items harvested from real save references (guaranteed-valid type+name).
  2. Ammo / cooling / mobility from the community yaml-docs dataset, filtered to
     vanilla+DLC (mod-only entries like *79, *_QS, trueg_*, GYRO* removed) and
     mapped to the DataAsset types confirmed against the save.
  3. A curated set of confident base weapon names following confirmed conventions.

The game safely ignores any PrimaryAssetId it does not recognise (e.g. an item
from a DLC you do not own) -- it just will not appear. You can also type a custom
asset name in the GUI.

Category -> inventory array:
  weapon -> WeaponInventory ; equipment & ammo -> EquipmentInventory
"""

WEAPONS = [
    ('Autocannon10', 'MWProjectileWeaponDataAsset'),
    ('Autocannon10_Burst_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('Autocannon10_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('Autocannon2', 'MWProjectileWeaponDataAsset'),
    ('Autocannon20', 'MWProjectileWeaponDataAsset'),
    ('Autocannon20_Auto_Lvl3', 'MWProjectileWeaponDataAsset'),
    ('Autocannon20_Burst_Lvl3', 'MWProjectileWeaponDataAsset'),
    ('Autocannon20_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('Autocannon2_Burst', 'MWProjectileWeaponDataAsset'),
    ('Autocannon2_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('Autocannon5', 'MWProjectileWeaponDataAsset'),
    ('Autocannon5_Auto_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('Autocannon5_Auto_Lvl3', 'MWProjectileWeaponDataAsset'),
    ('Autocannon5_Burst_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('Autocannon5_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('Axe_Heavy_Lvl2', 'MWMeleeWeaponDataAsset'),
    ('BattleAxe_Assault', 'MWMeleeWeaponDataAsset'),
    ('BinaryLaser', 'MWTraceWeaponDataAsset'),
    ('BinaryLaser_Lvl0', 'MWTraceWeaponDataAsset'),
    ('Claymore_Assault', 'MWMeleeWeaponDataAsset'),
    ('Claymore_Assault_Lvl3', 'MWMeleeWeaponDataAsset'),
    ('Flamer', 'MWTraceWeaponDataAsset'),
    ('Flamer_Lvl0', 'MWTraceWeaponDataAsset'),
    ('Gauss', 'MWProjectileWeaponDataAsset'),
    ('HammerFist_Light_Lvl0', 'MWMeleeWeaponDataAsset'),
    ('Hammer_Heavy', 'MWMeleeWeaponDataAsset'),
    ('HeavyRifle_Burst_Lvl2', 'MWProjectileWeaponDataAsset'),
    ('HeavyRifle_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('Katana_Assault', 'MWMeleeWeaponDataAsset'),
    ('Knuckles_Assault_Lvl2', 'MWMeleeWeaponDataAsset'),
    ('Knuckles_Heavy', 'MWMeleeWeaponDataAsset'),
    ('Knuckles_Light', 'MWMeleeWeaponDataAsset'),
    ('LRM10', 'MWMissileWeaponDataAsset'),
    ('LRM10_Lvl0', 'MWMissileWeaponDataAsset'),
    ('LRM10_Stream', 'MWMissileWeaponDataAsset'),
    ('LRM10_Stream_Lvl0', 'MWMissileWeaponDataAsset'),
    ('LRM15', 'MWMissileWeaponDataAsset'),
    ('LRM15_Stream', 'MWMissileWeaponDataAsset'),
    ('LRM15_Stream_Lvl0', 'MWMissileWeaponDataAsset'),
    ('LRM15_Stream_Lvl2', 'MWMissileWeaponDataAsset'),
    ('LRM20', 'MWMissileWeaponDataAsset'),
    ('LRM20_Stream', 'MWMissileWeaponDataAsset'),
    ('LRM5', 'MWMissileWeaponDataAsset'),
    ('LRM5_Stream', 'MWMissileWeaponDataAsset'),
    ('LRM5_Stream_Lvl0', 'MWMissileWeaponDataAsset'),
    ('LargeLaser', 'MWTraceWeaponDataAsset'),
    ('LargeLaser_Lvl0', 'MWTraceWeaponDataAsset'),
    ('LargeLaser_ShortBurst', 'MWTraceWeaponDataAsset'),
    ('LargeLaser_ShortBurst_Lvl0', 'MWTraceWeaponDataAsset'),
    ('LightRifle_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('MachineGun', 'MWTraceWeaponDataAsset'),
    ('MediumLaser', 'MWTraceWeaponDataAsset'),
    ('MediumLaser_Lvl0', 'MWTraceWeaponDataAsset'),
    ('MediumLaser_Lvl2', 'MWTraceWeaponDataAsset'),
    ('MediumLaser_ShortBurst', 'MWTraceWeaponDataAsset'),
    ('MediumLaser_ShortBurst_Lvl0', 'MWTraceWeaponDataAsset'),
    ('MediumLaser_ShortBurst_Lvl2', 'MWTraceWeaponDataAsset'),
    ('MediumRifle', 'MWProjectileWeaponDataAsset'),
    ('MediumRifle_Lvl0', 'MWProjectileWeaponDataAsset'),
    ('PPC', 'MWProjectileWeaponDataAsset'),
    ('SRM2', 'MWMissileWeaponDataAsset'),
    ('SRM2_Lvl0', 'MWMissileWeaponDataAsset'),
    ('SRM2_Stream', 'MWMissileWeaponDataAsset'),
    ('SRM4', 'MWMissileWeaponDataAsset'),
    ('SRM6', 'MWMissileWeaponDataAsset'),
    ('SRM6_Lvl0', 'MWMissileWeaponDataAsset'),
    ('SRM6_Stream', 'MWMissileWeaponDataAsset'),
    ('SmallLaser', 'MWTraceWeaponDataAsset'),
    ('SmallLaser_ShortBurst', 'MWTraceWeaponDataAsset'),
    ('SmallLaser_ShortBurst_Lvl0', 'MWTraceWeaponDataAsset'),
]

EQUIPMENT = [
    ('DoubleHeatSink', 'MWHeatSinkDataAsset'),
    ('ImprovedJumpJet_Class1_Equipment', 'MWJumpJetDataAsset'),
    ('ImprovedJumpJet_Class2_Equipment', 'MWJumpJetDataAsset'),
    ('ImprovedJumpJet_Class3_Equipment', 'MWJumpJetDataAsset'),
    ('ImprovedJumpJet_Class4_Equipment', 'MWJumpJetDataAsset'),
    ('ImprovedJumpJet_Class5_Equipment', 'MWJumpJetDataAsset'),
    ('JumpJet_Class1_Equipment', 'MWJumpJetDataAsset'),
    ('JumpJet_Class2_Equipment', 'MWJumpJetDataAsset'),
    ('JumpJet_Class3_Equipment', 'MWJumpJetDataAsset'),
    ('JumpJet_Class4_Equipment', 'MWJumpJetDataAsset'),
    ('JumpJet_Class5_Equipment', 'MWJumpJetDataAsset'),
    ('MASC_MKI', 'MWMASCDataAsset'),
    ('MASC_MKII', 'MWMASCDataAsset'),
    ('MASC_MKIII', 'MWMASCDataAsset'),
    ('MASC_MKIV', 'MWMASCDataAsset'),
    ('MASC_MKV', 'MWMASCDataAsset'),
    ('SUPERCHARGER_Arena_MKII', 'MWMASCDataAsset'),
    ('SingleHeatSink', 'MWHeatSinkDataAsset'),
    ('Supercharger_Arena_MKV', 'MWMASCDataAsset'),
    ('Supercharger_MKI', 'MWMASCDataAsset'),
    ('Supercharger_MKII', 'MWMASCDataAsset'),
    ('Supercharger_MKIII', 'MWMASCDataAsset'),
    ('Supercharger_MKIV', 'MWMASCDataAsset'),
    ('Supercharger_MKV', 'MWMASCDataAsset'),
]

AMMO = [
    ('AC10_LBX_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC10_LBX_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC10_Standard_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC10_Standard_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC20_Standard_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC20_Standard_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC2_Standard_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC2_Standard_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC5_Standard_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC5_Standard_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC5_Ultra_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AC5_Ultra_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AMS_AmmoEquipment', 'MWAmmoDataAsset'),
    ('AMS_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('Gauss_Standard_AmmoEquipment', 'MWAmmoDataAsset'),
    ('Gauss_Standard_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('HeavyRifle_AmmoEquipment', 'MWAmmoDataAsset'),
    ('HeavyRifle_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('LRM_AmmoEquipment', 'MWAmmoDataAsset'),
    ('LRM_Artemis_AmmoEquipment', 'MWAmmoDataAsset'),
    ('LRM_Artemis_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('LRM_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('LargeChemLaser_AmmoEquipment', 'MWAmmoDataAsset'),
    ('LargeChemLaser_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('LightRifle_AmmoEquipment', 'MWAmmoDataAsset'),
    ('LightRifle_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('MachineGun_Standard_AmmoEquipment', 'MWAmmoDataAsset'),
    ('MachineGun_Standard_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('MediumChemLaser_AmmoEquipment', 'MWAmmoDataAsset'),
    ('MediumChemLaser_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('MediumRifle_AmmoEquipment', 'MWAmmoDataAsset'),
    ('MediumRifle_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('NARC_AmmoEquipment', 'MWAmmoDataAsset'),
    ('NARC_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('SRM_AmmoEquipment', 'MWAmmoDataAsset'),
    ('SRM_Artemis_AmmoEquipment', 'MWAmmoDataAsset'),
    ('SRM_Artemis_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('SRM_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('SRM_Streak_AmmoEquipment', 'MWAmmoDataAsset'),
    ('SRM_Streak_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('SmallChemLaser_AmmoEquipment', 'MWAmmoDataAsset'),
    ('SmallChemLaser_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('TBolt10_AmmoEquipment', 'MWAmmoDataAsset'),
    ('TBolt10_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('TBolt15_AmmoEquipment', 'MWAmmoDataAsset'),
    ('TBolt15_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('TBolt20_AmmoEquipment', 'MWAmmoDataAsset'),
    ('TBolt20_Half_AmmoEquipment', 'MWAmmoDataAsset'),
    ('TBolt5_AmmoEquipment', 'MWAmmoDataAsset'),
    ('TBolt5_Half_AmmoEquipment', 'MWAmmoDataAsset'),
]

CATALOG = {"weapon": WEAPONS, "equipment": EQUIPMENT, "ammo": AMMO}
CATEGORY_INVENTORY = {"weapon": "weapon", "equipment": "equipment", "ammo": "equipment"}
