"""Curated pilot / mech trait asset-name catalog (issue #15).

The Add-Trait dropdowns are otherwise limited to traits the loaded save has
already referenced (SaveFile.referenced_traits), so traits the save has never
seen -- academy Graduate traits, the Specialist/Affinity traits, Cantina mech
traits, etc. -- could only be typed in by exact asset name. This catalog merges
known-good asset names into those dropdowns with a friendly label so traits are
searchable by their in-game name.

Data: 224 entries (167 pilot + 57 mech) contributed by FiendishDrWu (issue #15),
generated from game-derived MWPilotTraitDataAsset / MWMechTraitDataAsset exports.
Pilot-trait assets end in `_PilotTrait`; mech (Cantina) traits end in `_Trait`.
Both are added by asset name only, so this catalog needs no type column. The game
silently ignores unknown asset ids, so mod-added traits the save has referenced
still appear (harvested from the save); a trait not in the save and not here can
be typed in by asset name.
"""

# (asset_name, friendly_label) -- pilot traits (MWPilotTraitDataAsset).
PILOT_TRAITS = [
    ('Affinity_Assault_PilotTrait', "Assault 'Mech Affinity"),
    ('BadPatient_PilotTrait', 'Bad Patient'),
    ('Bookworm_PilotTrait', 'Bookworm'),
    ('Background_ConArtist_PilotTrait', 'Con Artist'),
    ('FastLearner_PilotTrait', 'Fast Learner'),
    ('Firebug_PilotTrait', 'Firebug'),
    ('Frail_PilotTrait', 'Frail'),
    ('Frugal_PilotTrait', 'Frugal'),
    ('Greedy_PilotTrait', 'Greedy'),
    ('Hands-OnLearner_PilotTrait', 'Hands-on Learner'),
    ('Hearty_PilotTrait', 'Hearty'),
    ('Affinity_Heavy_PilotTrait', "Heavy 'Mech Affinity"),
    ('HotDog_PilotTrait', 'Hot Dog'),
    ('Hypochondriac_PilotTrait', 'Hypochondriac'),
    ('Affinity_Freeman_Jenner_PilotTrait', "Jenner 'Mech Affinity"),
    ('Specialist_Laser_PilotTrait', 'Laser Specialist'),
    ('Affinity_Light_PilotTrait', "Light 'Mech Affinity"),
    ('Specialist_LRM_PilotTrait', 'LRM Specialist'),
    ('Affinity_Medium_PilotTrait', "Medium 'Mech Affinity"),
    ('Graduate_NAIS_PilotTrait', 'NAIS Graduate'),
    ('Graduate_Nargelring_PilotTrait', 'Nargelring Graduate'),
    ('Background_OldMoney_PilotTrait', 'Old Money'),
    ('Specialist_PointBlank_PilotTrait', 'Point Blank Specialist'),
    ('Precise_PilotTrait', 'Precise'),
    ('Graduate_Princefield_PilotTrait', 'Princefield Graduate'),
    ('QuickHealer_PilotTrait', 'Quick Healer'),
    ('Background_Scrapper_PilotTrait', 'Scrapper'),
    ('Specialist_SRM_PilotTrait', 'SRM Specialist'),
    ('Specialist_Autocannon_PilotTrait', 'standard Autocannon Specialist'),
    ('Graduate_SunZhang_PilotTrait', 'Sun Zhang Graduate'),
    ('Survivor_PilotTrait', 'Survivor'),
    ('Affinity_Annihilator_Chassis_PilotTrait', "Annihilator 'Mech Affinity"),
    ('Affinity_Archer_Chassis_PilotTrait', "Archer 'Mech Affinity"),
    ('Affinity_Assassin_Chassis_PilotTrait', "Assassin 'Mech Affinity"),
    ('Affinity_Atlas_Chassis_PilotTrait', "Atlas 'Mech Affinity"),
    ('Affinity_Awesome_Chassis_PilotTrait', "Awesome 'Mech Affinity"),
    ('Affinity_Banshee_Chassis_PilotTrait', "Banshee 'Mech Affinity"),
    ('Affinity_BattleMaster_Chassis_PilotTrait', "BattleMaster 'Mech Affinity"),
    ('Affinity_BlackKnight_Chassis_PilotTrait', "Black Knight 'Mech Affinity"),
    ('Affinity_Blackjack_Chassis_PilotTrait', "Blackjack 'Mech Affinity"),
    ('Affinity_Bushwacker_Chassis_PilotTrait', "Bushwacker 'Mech Affinity"),
    ('Affinity_Cataphract_Chassis_PilotTrait', "Cataphract 'Mech Affinity"),
    ('Affinity_Catapult_Chassis_PilotTrait', "Catapult 'Mech Affinity"),
    ('Affinity_Centurion_Chassis_PilotTrait', "Centurion 'Mech Affinity"),
    ('Affinity_Champion_Chassis_PilotTrait', "Champion 'Mech Affinity"),
    ('Affinity_Charger_Chassis_PilotTrait', "Charger 'Mech Affinity"),
    ('Affinity_Cicada_Chassis_PilotTrait', "Cicada 'Mech Affinity"),
    ('Affinity_Commando_Chassis_PilotTrait', "Commando 'Mech Affinity"),
    ('Affinity_Crab_Chassis_PilotTrait', "Crab 'Mech Affinity"),
    ('Affinity_Crusader_Chassis_PilotTrait', "Crusader 'Mech Affinity"),
    ('Affinity_Cyclops_Chassis_PilotTrait', "Cyclops 'Mech Affinity"),
    ('Affinity_Dervish_Chassis_PilotTrait', "Dervish 'Mech Affinity"),
    ('Affinity_Dragon_Chassis_PilotTrait', "Dragon 'Mech Affinity"),
    ('Affinity_Enforcer_Chassis_PilotTrait', "Enforcer 'Mech Affinity"),
    ('Affinity_Firestarter_Chassis_PilotTrait', "Firestarter 'Mech Affinity"),
    ('Affinity_Flea_Chassis_PilotTrait', "Flea 'Mech Affinity"),
    ('Affinity_Grasshopper_Chassis_PilotTrait', "Grasshopper 'Mech Affinity"),
    ('Affinity_Griffin_Chassis_PilotTrait', "Griffin 'Mech Affinity"),
    ('Affinity_Hatamoto-Chi_Chassis_PilotTrait', "Hatamoto-Chi 'Mech Affinity"),
    ('Affinity_Hatchetman_Chassis_PilotTrait', "Hatchetman 'Mech Affinity"),
    ('Affinity_Highlander_Chassis_PilotTrait', "Highlander 'Mech Affinity"),
    ('Affinity_Hunchback_Chassis_PilotTrait', "Hunchback 'Mech Affinity"),
    ('Affinity_JagerMech_Chassis_PilotTrait', "JagerMech 'Mech Affinity"),
    ('Affinity_Javelin_Chassis_PilotTrait', "Javelin 'Mech Affinity"),
    ('Affinity_Jenner_Chassis_PilotTrait', "Jenner 'Mech Affinity"),
    ('Affinity_KingCrab_Chassis_PilotTrait', "King Crab 'Mech Affinity"),
    ('Affinity_Kintaro_Chassis_PilotTrait', "Kintaro 'Mech Affinity"),
    ('Affinity_Loaderking_Chassis_PilotTrait', "Loaderking 'Mech Affinity"),
    ('Affinity_Locust_Chassis_PilotTrait', "Locust 'Mech Affinity"),
    ('Affinity_Longbow_Chassis_PilotTrait', "Longbow 'Mech Affinity"),
    ('Affinity_Marauder_Chassis_PilotTrait', "Marauder 'Mech Affinity"),
    ('Affinity_Mauler_Chassis_PilotTrait', "Mauler 'Mech Affinity"),
    ('Affinity_Orion_Chassis_PilotTrait', "Orion 'Mech Affinity"),
    ('Affinity_Panther_Chassis_PilotTrait', "Panther 'Mech Affinity"),
    ('Affinity_PhoenixHawk_Chassis_PilotTrait', "Phoenix Hawk 'Mech Affinity"),
    ('Affinity_Quickdraw_Chassis_PilotTrait', "Quickdraw 'Mech Affinity"),
    ('Affinity_Raven_Chassis_PilotTrait', "Raven 'Mech Affinity"),
    ('Affinity_Rifleman_Chassis_PilotTrait', "Rifleman 'Mech Affinity"),
    ('Affinity_ShadowHawk_Chassis_PilotTrait', "Shadow Hawk 'Mech Affinity"),
    ('Affinity_Spider_Chassis_PilotTrait', "Spider 'Mech Affinity"),
    ('Affinity_Stalker_Chassis_PilotTrait', "Stalker 'Mech Affinity"),
    ('Affinity_Sunder_Chassis_PilotTrait', "Sunder 'Mech Affinity"),
    ('Affinity_Thunderbolt_Chassis_PilotTrait', "Thunderbolt 'Mech Affinity"),
    ('Affinity_Trebuchet_Chassis_PilotTrait', "Trebuchet 'Mech Affinity"),
    ('Affinity_UrbanMech_Chassis_PilotTrait', "UrbanMech 'Mech Affinity"),
    ('Affinity_Victor_Chassis_PilotTrait', "Victor 'Mech Affinity"),
    ('Affinity_Vindicator_Chassis_PilotTrait', "Vindicator 'Mech Affinity"),
    ('Affinity_Vulcan_Chassis_PilotTrait', "Vulcan 'Mech Affinity"),
    ('Affinity_Warhammer_Chassis_PilotTrait', "Warhammer 'Mech Affinity"),
    ('Affinity_Wolfhound_Chassis_PilotTrait', "Wolfhound 'Mech Affinity"),
    ('Affinity_Wolverine_Chassis_PilotTrait', "Wolverine 'Mech Affinity"),
    ('Affinity_Zeus_Chassis_PilotTrait', "Zeus 'Mech Affinity"),
    ('Criminal_Marik_PilotTrait', 'Criminal (Free Worlds League)'),
    ('Criminal_Davion_PilotTrait', 'Criminal (House Davion)'),
    ('Criminal_Kurita_PilotTrait', 'Criminal (House Kurita)'),
    ('Criminal_Liao_PilotTrait', 'Criminal (House Liao)'),
    ('Criminal_Steiner_PilotTrait', 'Criminal (House Steiner)'),
    ('Noble_Marik_PilotTrait', 'Free Worlds League Noble'),
    ('Patriot_Marik_PilotTrait', 'Free Worlds League Patriot'),
    ('Hatred_Marik_PilotTrait', 'Hates Free Worlds League'),
    ('Hatred_Davion_PilotTrait', 'Hates House Davion'),
    ('Hatred_Kurita_PilotTrait', 'Hates House Kurita'),
    ('Hatred_Liao_PilotTrait', 'Hates House Liao'),
    ('Hatred_Steiner_PilotTrait', 'Hates House Steiner'),
    ('Noble_Davion_PilotTrait', 'House Davion Noble'),
    ('Patriot_Davion_PilotTrait', 'House Davion Patriot'),
    ('Noble_Kurita_PilotTrait', 'House Kurita Noble'),
    ('Patriot_Kurita_PilotTrait', 'House Kurita Patriot'),
    ('Noble_Liao_PilotTrait', 'House Liao Noble'),
    ('Patriot_Liao_PilotTrait', 'House Liao Patriot'),
    ('Noble_Steiner_PilotTrait', 'House Steiner Noble'),
    ('Patriot_Steiner_PilotTrait', 'House Steiner Patriot'),
    ('Master_Autocannon10_PilotTrait', 'AC/10 Master'),
    ('Master_Autocannon2_PilotTrait', 'AC/2 Master'),
    ('Master_Autocannon20_PilotTrait', 'AC/20 Master'),
    ('Master_Autocannon5_PilotTrait', 'AC/5 Master'),
    ('Specialist_Arena_PilotTrait', 'Arena Specialist'),
    ('BitterEnd_PilotTrait', 'Bitter End'),
    ('Affinity_BlackHawk_Chassis_PilotTrait', "Black Hawk 'Mech Affinity"),
    ('Bulwark_PilotTrait', 'Bulwark'),
    ('Affinity_CauldronBorn_Chassis_PilotTrait', "Cauldron-Born 'Mech Affinity"),
    ('Background_ClanGhostBear_PilotTrait', 'Clan Ghost Bear Origins'),
    ('Background_ClanJadeFalcon_PilotTrait', 'Clan Jade Falcon Origins'),
    ('Background_ClanSmokeJaguar_PilotTrait', 'Clan Smoke Jaguar Origins'),
    ('Background_ClanWolf_PilotTrait', 'Clan Wolf Origins'),
    ('ClusterHitter_PilotTrait', 'Cluster Hitter'),
    ('Affinity_Daishi_Chassis_PilotTrait', "Daishi 'Mech Affinity"),
    ('Affinity_Firemoth_Chassis_PilotTrait', "Dasher 'Mech Affinity"),
    ('Affinity_Dragonfly_Chassis_PilotTrait', "Dragonfly 'Mech Affinity"),
    ('EagleEyes_PilotTrait', 'Eagle Eyes'),
    ('Affinity_Gladiator_Chassis_PilotTrait', "Gladiator 'Mech Affinity"),
    ('Affinity_Kodiak_Chassis_PilotTrait', "Kodiak 'Mech Affinity"),
    ('Affinity_Koshi_Chassis_PilotTrait', "Koshi 'Mech Affinity"),
    ('Master_Laser_PilotTrait', 'Laser Master'),
    ('Affinity_Linebacker_Chassis_PilotTrait', "Linebacker 'Mech Affinity"),
    ('Affinity_Loki_Chassis_PilotTrait', "Loki 'Mech Affinity"),
    ('Affinity_MadCat_Chassis_PilotTrait', "Mad Cat 'Mech Affinity"),
    ('Affinity_ManOWar_Chassis_PilotTrait', "Man O' War 'Mech Affinity"),
    ('Affinity_Masakari_Chassis_PilotTrait', "Masakari 'Mech Affinity"),
    ('Affinity_Naga_Chassis_PilotTrait', "Naga 'Mech Affinity"),
    ('Affinity_NightGyr_Chassis_PilotTrait', "Night Gyr 'Mech Affinity"),
    ('Affinity_Puma_Chassis_PilotTrait', "Puma 'Mech Affinity"),
    ('Affinity_Ryoken_Chassis_PilotTrait', "Ryoken 'Mech Affinity"),
    ('Affinity_Shadowcat_Chassis_PilotTrait', "Shadow Cat 'Mech Affinity"),
    ('SpeedDemon_PilotTrait', 'Speed Demon'),
    ('Affinity_Thor_Chassis_PilotTrait', "Thor 'Mech Affinity"),
    ('TriggerDiscipline_PilotTrait', 'Trigger Discipline'),
    ('Affinity_Uller_Chassis_PilotTrait', "Uller 'Mech Affinity"),
    ('Unbreakable_PilotTrait', 'Unbreakable'),
    ('Affinity_Vixen_Chassis_PilotTrait', "Vixen 'Mech Affinity"),
    ('Affinity_Vulture_Chassis_PilotTrait', "Vulture 'Mech Affinity"),
    ('Expert_AC10_PilotTrait', 'AC/10 Expert'),
    ('Expert_AC2_PilotTrait', 'AC/2 Expert'),
    ('Expert_AC20_PilotTrait', 'AC/20 Expert'),
    ('Expert_AC5_PilotTrait', 'AC/5 Expert'),
    ('Expert_GaussRifle_PilotTrait', 'Gauss Rifle Expert'),
    ('Expert_LargeLaser_PilotTrait', 'Large Laser Expert'),
    ('Expert_LRM10_PilotTrait', 'LRM 10 Expert'),
    ('Expert_LRM15_PilotTrait', 'LRM 15 Expert'),
    ('Expert_LRM20_PilotTrait', 'LRM 20 Expert'),
    ('Expert_LRM5_PilotTrait', 'LRM 5 Expert'),
    ('Expert_MediumLaser_PilotTrait', 'Medium Laser Expert'),
    ('Expert_MRM_PilotTrait', 'MRM Expert'),
    ('Expert_SmallLaser_PilotTrait', 'Small Laser Expert'),
    ('Expert_SRM2_PilotTrait', 'SRM 2 Expert'),
    ('Expert_SRM4_PilotTrait', 'SRM 4 Expert'),
    ('Expert_SRM6_PilotTrait', 'SRM 6 Expert'),
]

# (asset_name, friendly_label) -- mech / Cantina traits (MWMechTraitDataAsset).
MECH_TRAITS = [
    ('IncreasedArmor_Trait1', 'Refined Armor I'),
    ('IncreasedArmor_Trait2', 'Refined Armor II'),
    ('TargetingComputerMk1_Trait', 'Targeting Computer Mk1'),
    ('TargetingComputerMk2_Trait', 'Targeting Computer Mk2'),
    ('TargetingComputerMk3_Trait', 'Targeting Computer Mk3'),
    ('TargetingComputerMk4_Trait', 'Targeting Computer Mk4'),
    ('TargetingComputerMk5_Trait', 'Targeting Computer Mk5'),
    ('TargetingComputerMk6_Trait', 'Targeting Computer Mk6'),
    ('TargetingComputerMk7_Trait', 'Targeting Computer Mk7'),
    ('IncreasedHeatCooling_Trait1', 'Faster Cooling'),
    ('IncreasedHeatCapacity_Trait1', 'Heat Containment I'),
    ('IncreasedHeatCapacity_Trait2', 'Heat Containment II'),
    ('ReducedHeatGeneration_Trait1', 'Reduced Heat Spikes'),
    ('IncreasedTurnSpeed_Trait1', 'Anchor Turn I'),
    ('IncreasedTurnSpeed_Trait2', 'Anchor Turn II'),
    ('IncreasedTopSpeed_Trait1', 'Boosted Top Speed'),
    ('IncreasedJJAccelXYZ_Trait1', 'Jump Jet Thrust'),
    ('IncreasedJJFuelBurnTime_Trait1', 'Longer Burn Time'),
    ('IncreasedJJFuelRegenTime_Trait1', 'Rapid Jump Jet Recharge'),
    ('IncreasedAccelerationDeceleration_Trait1', 'Responsive Movement I'),
    ('IncreasedAccelerationDeceleration_Trait2', 'Responsive Movement II'),
    ('IncreasedTorsoTwistRate_Trait1', 'Torso Twist Speed'),
    ('IncreasedSensorRange_Trait1', 'Expanded Sensor Range I'),
    ('IncreasedSensorRange_Trait2', 'Expanded Sensor Range II'),
    ('IncreasedStructure_Trait1', 'Fortified Internal Structure I'),
    ('IncreasedStructure_Trait2', 'Fortified Internal Structure II'),
    ('IncreasedEnergyRangeAndSpeed_Trait1', 'Accurate Focusing Arrays I'),
    ('IncreasedEnergyRangeAndSpeed_Trait2', 'Accurate Focusing Arrays II'),
    ('IncreasedMissileRangeAndSpeed_Trait1', 'Aerodynamic Hull I'),
    ('IncreasedMissileRangeAndSpeed_Trait2', 'Aerodynamic Hull II'),
    ('ReducedBallisticHeat_Trait1', 'Ballistic Heat Transfer I'),
    ('ReducedBallisticHeat_Trait2', 'Ballistic Heat Transfer II'),
    ('ReducedEnergyCooldown_Trait1', 'Condensed Cycle Time I'),
    ('ReducedEnergyCooldown_Trait2', 'Condensed Cycle Time II'),
    ('IncreasedWeaponDamage_Trait1', 'Damage Tuning'),
    ('IncreasedEnergyDamage_Trait1', 'Enhanced Energy Output I'),
    ('IncreasedEnergyDamage_Trait2', 'Enhanced Energy Output II'),
    ('ReducedMissileCooldown_Trait1', 'Faster Missile Reload I'),
    ('ReducedMissileCooldown_Trait2', 'Faster Missile Reload II'),
    ('IncreasedBallisticRangeAndSpeed_Trait1', 'Faster Projectiles I'),
    ('IncreasedBallisticRangeAndSpeed_Trait2', 'Faster Projectiles II'),
    ('ReducedWeaponCooldown_Trait1', 'Faster Weapon Cycling'),
    ('IncreasedWeaponRangeAndSpeed_Trait1', 'Improved Range'),
    ('ReducedMissileHeat_Trait1', 'Missile Exhaust Venting I'),
    ('ReducedMissileHeat_Trait2', 'Missile Exhaust Venting II'),
    ('IncreasedMissileDamage_Trait1', 'Potent Warheads I'),
    ('IncreasedMissileDamage_Trait2', 'Potent Warheads II'),
    ('ReducedBallisticCooldown_Trait1', 'Quick Ammo Feed I'),
    ('ReducedBallisticCooldown_Trait2', 'Quick Ammo Feed II'),
    ('ReducedEnergyHeat_Trait1', 'Reduced Power Consumption I'),
    ('ReducedEnergyHeat_Trait2', 'Reduced Power Consumption II'),
    ('ReducedLaserDuration_Trait1', 'Shorter Burn Time'),
    ('IncreasedBallisticDamage_Trait1', 'Superior Detonation I'),
    ('IncreasedBallisticDamage_Trait2', 'Superior Detonation II'),
    ('IncreasedLockRetentionAndLoseLockTime_Trait1', 'Target Lock Retention'),
    ('ReducedMissileSpread_Trait1', 'Tighter Missile Clusters'),
    ('ReducedWeaponHeat_Trait1', 'Weapon Heat Transfer'),
]

_SEP = " -- "  # asset names never contain this


def display(asset: str, label: str | None = None) -> str:
    """Dropdown display string for a trait: 'Asset -- Friendly Label'."""
    return f"{asset}{_SEP}{label}" if label else asset


def dropdown_values(save_names, catalog) -> list[str]:
    """Merge save-harvested asset names with the curated catalog into sorted
    display strings (catalog entries get their friendly label)."""
    labels = dict(catalog)
    names = set(save_names) | set(labels)
    return sorted((display(n, labels.get(n)) for n in names), key=str.lower)


def resolve(text: str) -> str:
    """A dropdown display string (or raw typed name) -> bare asset name."""
    return text.split(_SEP, 1)[0].strip()
